# Generated by Django 6.0.3 on 2026-05-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('subscription', 'period_start', 'period_end'), name='unique_invoice_per_subscription_period'),
        ),
    ]
