# Generated by Django 6.0.3 on 2026-05-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_membership_and_invitation'),
    ]

    operations = [
    ]
