# Generated by Django 6.0.3 on 2026-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_owner_memberships'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('organization',), name='unique_org_owner'),
        ),
    ]
