"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'corsheaders',
    'accounts',
    'plans',
    'subscriptions',
    'invoices',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.environ.get('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ['POSTGRES_USER'],
            'PASSWORD': os.environ['POSTGRES_PASSWORD'],
            'HOST': os.environ['POSTGRES_HOST'],
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "accounts.authentication.ApiKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Throttling is backed by the shared cache (see CACHES), so counters are
    # enforced across gunicorn workers and instances. The default class covers
    # every route by tenant; auth endpoints override it with a per-IP scope.
    "DEFAULT_THROTTLE_CLASSES": [
        "accounts.throttling.OrganizationRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "org": os.environ.get("THROTTLE_RATE_ORG", "100/min"),
        "auth_register": os.environ.get("THROTTLE_RATE_REGISTER", "5/min"),
        "auth_login": os.environ.get("THROTTLE_RATE_LOGIN", "5/min"),
    },
    # How many trusted proxies sit in front of the app. Left unset, DRF derives
    # the throttle IP straight from the client-supplied X-Forwarded-For header,
    # so a spoofed header lands each request in a fresh bucket and defeats the
    # per-IP auth throttle. Default 0 (gunicorn is exposed directly) makes DRF
    # trust only REMOTE_ADDR; behind N trusted proxies set DRF_NUM_PROXIES=N so
    # it reads the (N+1)th-from-last XFF entry instead.
    "NUM_PROXIES": int(os.environ.get("DRF_NUM_PROXIES", "0")),
}

# Throttle counters live here. A shared Redis cache makes the limits fleet-wide;
# without REDIS_THROTTLE_URL (local runserver / CI) we fall back to per-process
# memory, which still works for a single instance.
REDIS_THROTTLE_URL = os.environ.get("REDIS_THROTTLE_URL", "")
if REDIS_THROTTLE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_THROTTLE_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

SPECTACULAR_SETTINGS = {
    "TITLE": "Chargeflow API",
    "DESCRIPTION": "Modular Django billing engine - plans, subscriptions, invoices, and payments.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {
        "RoleEnum": "accounts.models.OrganizationMembership.Role",
    },
}

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "formatters": {
        "simple": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    # Root handler so every app logger (invoices.tasks, subscriptions.tasks, …)
    # reaches the console. Under Celery the worker attaches its own root handler,
    # but runserver / eager mode has none, so batch logger.exception() calls
    # would otherwise vanish.
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "infrastructure": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Celery / background jobs
# In production, docker-compose sets a separate worker/beat consume the queue.
# Without a broker, tasks run inline
# so local `runserver` and CI need no Redis and no worker process.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "")
CELERY_TASK_ALWAYS_EAGER = not CELERY_BROKER_URL
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = "UTC"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BEAT_SCHEDULE = {
    "run-dunning-hourly": {
        "task": "invoices.tasks.run_dunning",
        "schedule": crontab(minute=0),
    },
    # Staggered off dunning so the cycles don't pile onto the same minute.
    "run-renewals-hourly": {
        "task": "subscriptions.tasks.run_renewals",
        "schedule": crontab(minute=15),
    },
    "run-trial-activations-hourly": {
        "task": "subscriptions.tasks.run_trial_activations",
        "schedule": crontab(minute=30),
    },
}

# Mock payment provider: share of charges that are randomly declined (0.0-1.0).
# Defaults to 0 so local runs and tests are deterministic; docker sets 0.5
PAYMENT_FAILURE_RATE = float(os.environ.get("PAYMENT_FAILURE_RATE", "0"))
