# Generated by Django 6.0.3 on 2026-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='canceled_reason',
            field=models.CharField(blank=True, choices=[('voluntary', 'Voluntary'), ('non_payment', 'Non-payment')], max_length=20, null=True),
        ),
    ]
